server:
  port: 8080

spring:
  application:
    name: ShardingSphere
  # 环境 dev|test|prod
#  profiles:
#    active: dev
  main:
    allow-bean-definition-overriding: true
  config:
    import: classpath:datasource-sharding-test.yml

